pick_pallet_23:
  task_id: "TASK023"
  steps:
    - type: ctrl
      source: LM49
      target: LM51
      operation: ForkHeight
      end_height: 1.5

    - type: ctrl
      source: LM51
      target: AP50
      operation: ForkLoad
      end_height: 1.555

    - type: ctrl
      source: AP50
      target: LM51
      operation: ForkHeight
      end_height: 0.16

    - type: nav
      source: LM51
      target: LM49

place_pallet_23:
  task_id: "TASK023"
  steps:
    - type: ctrl
      source: LM49
      target: LM51
      operation: ForkHeight
      end_height: 1.565

    - type: ctrl
      source: LM51
      target: AP50
      operation: ForkUnload
      end_height: 1.5

    - type: ctrl
      source: AP50
      target: LM51
      operation: ForkHeight
      end_height: 0.085

    - type: nav
      source: LM51
      target: LM49

pick_pallet_22:
  task_id: "TASK022"
  steps:
    - type: ctrl
      source: LM49
      target: LM51
      operation: ForkHeight
      end_height: 0.085

    - type: ctrl
      source: LM51
      target: AP50
      operation: ForkLoad
      end_height: 0.15

    - type: ctrl
      source: AP50
      target: LM51
      operation: ForkHeight
      end_height: 0.15

    - type: nav
      source: LM51
      target: LM49

place_pallet_22:
  task_id: "TASK022"
  steps:
    - type: ctrl
      source: LM49
      target: LM51

    - type: ctrl
      source: LM51
      target: AP50
      operation: ForkUnload
      end_height: 0.085

    - type: ctrl
      source: AP50
      target: LM51

    - type: nav
      source: LM51
      target: LM49
