seer:
  # สำหรับ Robot Status API
  status_ip: "192.168.0.181"
  status_port: 19204
  status_api: 1020

  # สำหรับ Path Navigation API
  nav_ip: "192.168.0.181"
  nav_port: 19206
  nav_api: 3051
  nav_batch_api: 3066

  timeout_sec: 5
