# Robot Parameters Configuration
# This file contains robot-specific parameters for the fleet

robots:
  robot_01:
    robot_name: "SEER_Robot_01"
    robot_id: 1
    robot_ip: "192.168.0.180"
    description: "Primary SEER Robot"
    
  robot_02:
    robot_name: "SEER_Robot_02"
    robot_id: 2
    robot_ip: "192.168.0.181"
    description: "Secondary SEER Robot"

